name: Mise à jour Hebdomadaire Momentum

on:
  schedule:
    # Se lance tous les lundis à 8h00 UTC (9h ou 10h en France)
    - cron: '0 8 * * 1'
  # Permet aussi de lancer le bot manuellement via un bouton pour tester
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Récupération du code
      uses: actions/checkout@v3

    - name: Installation de Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Installation des librairies
      run: |
        pip install -r requirements.txt

    - name: Lancement du Bot Momentum
      run: |
        python bot.py

    - name: Sauvegarde et Mise à jour du site
      run: |
        git config --global user.name 'MomentumBot'
        git config --global user.email 'bot@noreply.github.com'
        git add data.json
        git commit -m "Mise à jour automatique des actions" || echo "Rien à modifier"
        git push
